// Code generated by AsyncAPI. DO NOT EDIT.
// Source: asyncapi/asyncapi.yaml

package event

// PostgreSQL NOTIFY names for reconstructable realtime signals
const (
	SignalTranscodeProgress        = "transcode.progress"
	SignalTranscodeCancel          = "transcode.cancel"
	SignalWaveformProgress         = "waveform.progress"
	SignalWaveformCancel           = "waveform.cancel"
	SignalMeshOptimizationProgress = "mesh.optimization.progress"
	SignalMediaProcessingLifecycle = "media.processing.lifecycle"
	SignalOgLifecycle              = "og.lifecycle"
	SignalMailAdapterChanged       = "mail_adapter.changed"
	SignalContentUpdated           = "content.updated"
	SignalFileIngest               = "file.ingest"
	SignalTranslationLifecycle     = "translation.lifecycle"
)

// Queue names for direct work and durable consumer queues
const (
	QueueOgGenerate                          = "og.generate"
	QueueTranscoderAudio                     = "transcoder.audio"
	QueueTranscoderVideo                     = "transcoder.video"
	QueueWaveformGenerate                    = "waveform.generate"
	QueueAssetOptimizerMesh                  = "asset_optimizer.mesh"
	QueueFileDelete                          = "file.delete"
	QueueEmailSend                           = "email.send"
	QueueEmailAuth                           = "email.auth"
	QueueEmailCampaign                       = "email.campaign"
	QueueUserDeleteIdentity                  = "user.delete.identity"
	QueueUserDeleteAvatar                    = "user.delete.avatar"
	QueueAiMetadataGenerate                  = "ai.metadata.generate"
	QueueTranslationGenerate                 = "translation.generate"
	QueueTranscodeResult                     = "transcode.result"
	QueueWaveformResult                      = "waveform.result"
	QueueMeshOptimizationResult              = "mesh.optimization.result"
	QueueReleaseTrackOriginalAudioProjection = "release.track_original_audio.projection"
)

// Signal types for the fileIngest channel.
const (
	SignalTypeFileIngestUpload    = "upload"
	SignalTypeFileIngestDownload  = "download"
	SignalTypeFileIngestFinalized = "finalized"
	SignalTypeFileIngestAttached  = "attached"
	SignalTypeFileIngestFailed    = "failed"
)

// Content type constants
const (
	ContentTypeProtobuf = "application/x-protobuf"
	ContentTypeJSON     = "application/json"
)
