// Code generated by AsyncAPI translation request artifact template. DO NOT EDIT.
// Source: proto/api/manage/v1/translation.proto

package event

import (
	"errors"
	"strings"

	managev1 "github.com/echovisionlab/geul-event-contracts/gen/api/manage/v1"
)

// ValidateTranslationJobRequestArtifact validates the one request identity
// shared by every translation-capable domain. Domain-specific source epochs,
// hashes, and revision counters are intentionally not part of this boundary.
func ValidateTranslationJobRequestArtifact(job *managev1.TranslationJob) error {
	if job == nil || job.Target == nil {
		return errors.New("translation job target is required")
	}
	if strings.TrimSpace(job.RequestArtifactDigest) == "" {
		return errors.New("translation job request artifact digest is required")
	}
	return nil
}
