import { File, Text } from "@asyncapi/generator-react-sdk";

// Helper to convert channel name to PascalCase
function toPascalCase(str) {
  if (!str || typeof str !== "string") return "";
  return str
    .replace(/[-_.]/g, " ")
    .split(" ")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("");
}

export default function ({ asyncapi }) {
  // Get all channels - v3 API
  const channelsMap = asyncapi.allChannels();

  // Separate PGMQ queues from reconstructable PostgreSQL signals.
  const signals = [];
  const queues = [];
  const signalTypeGroups = [];

  if (channelsMap) {
    channelsMap.forEach((channel) => {
      const name = channel.id();
      const address = channel.address();
      const channelJson = channel.json ? channel.json() : {};
      const signalTypes = channelJson["x-signal-types"];
      const channelKind = channelJson["x-channel-kind"];

      if (Array.isArray(signalTypes) && signalTypes.length > 0) {
        signalTypeGroups.push({ name, keys: signalTypes });
      }

      if (channelKind === "durable_queue") {
        queues.push({ name, address });
      } else if (channelKind === "signal") {
        signals.push({ name, address });
      }
    });
  }

  return (
    <File name="constants.go">
      <Text>
        {`// Code generated by AsyncAPI. DO NOT EDIT.
// Source: asyncapi/asyncapi.yaml

package event

// PostgreSQL NOTIFY names for reconstructable realtime signals
const (
${signals.map((signal) => `\tSignal${toPascalCase(signal.name)} = "${signal.address}"`).join("\n")}
)

// Queue names for direct work and durable consumer queues
const (
${queues.map((q) => `\tQueue${toPascalCase(q.name)} = "${q.address}"`).join("\n")}
)

${signalTypeGroups
  .map(
    (group) => `// Signal types for the ${group.name} channel.
const (
${group.keys
  .map(
    (key) =>
      `\tSignalType${toPascalCase(group.name)}${toPascalCase(key)} = "${key}"`,
  )
  .join("\n")}
)`,
  )
  .join("\n\n")}

// Content type constants
const (
\tContentTypeProtobuf = "application/x-protobuf"
\tContentTypeJSON     = "application/json"
)
`}
      </Text>
    </File>
  );
}
