import { File, Text } from "@asyncapi/generator-react-sdk";

// Helper to convert channel name to camelCase
function toCamelCase(str) {
  if (!str || typeof str !== "string") return "";
  const pascal = str
    .replace(/[-_.]/g, " ")
    .split(" ")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("");
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function toPascalCase(str) {
  const camel = toCamelCase(str);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

export default function ({ asyncapi }) {
  // Get all channels - v3 API
  const channelsMap = asyncapi.allChannels();

  // Separate PGMQ queues from reconstructable PostgreSQL signals.
  const signals = [];
  const queues = [];
  const signalTypeGroups = [];

  if (channelsMap) {
    channelsMap.forEach((channel) => {
      const name = channel.id();
      const address = channel.address();
      const channelJson = channel.json ? channel.json() : {};
      const signalTypes = channelJson["x-signal-types"];
      const channelKind = channelJson["x-channel-kind"];

      if (Array.isArray(signalTypes) && signalTypes.length > 0) {
        signalTypeGroups.push({ name, keys: signalTypes });
      }

      if (channelKind === "durable_queue") {
        queues.push({ name, address });
      } else if (channelKind === "signal") {
        signals.push({ name, address });
      }
    });
  }

  return (
    <File name="generated.ts">
      <Text>
        {`// Code generated by AsyncAPI. DO NOT EDIT.
// Source: asyncapi/asyncapi.yaml

/**
 * PostgreSQL NOTIFY names for reconstructable realtime signals
 */
export const Signals = {
${signals.map((signal) => `  ${toCamelCase(signal.name)}: '${signal.address}',`).join("\n")}
} as const;

/**
 * Queue names for direct work and durable consumer queues
 */
export const Queues = {
${queues.map((q) => `  ${toCamelCase(q.name)}: '${q.address}',`).join("\n")}
} as const;

${signalTypeGroups
  .map(
    (group) => `export const ${toPascalCase(group.name)}SignalTypes = {
${group.keys.map((key) => `  ${toCamelCase(key)}: '${key}',`).join("\n")}
} as const;`,
  )
  .join("\n\n")}

/**
 * Content type constants
 */
export const ContentType = {
  protobuf: 'application/x-protobuf',
  json: 'application/json',
} as const;
`}
      </Text>
    </File>
  );
}
