// Code generated by AsyncAPI. DO NOT EDIT.
// Source: asyncapi/asyncapi.yaml

/**
 * PostgreSQL NOTIFY names for reconstructable realtime signals
 */
export const Signals = {
  transcodeProgress: "transcode.progress",
  transcodeCancel: "transcode.cancel",
  waveformProgress: "waveform.progress",
  waveformCancel: "waveform.cancel",
  meshOptimizationProgress: "mesh.optimization.progress",
  mediaProcessingLifecycle: "media.processing.lifecycle",
  ogLifecycle: "og.lifecycle",
  mailAdapterChanged: "mail_adapter.changed",
  contentUpdated: "content.updated",
  fileIngest: "file.ingest",
  translationLifecycle: "translation.lifecycle",
} as const;

/**
 * Queue names for direct work and durable consumer queues
 */
export const Queues = {
  ogGenerate: "og.generate",
  transcoderAudio: "transcoder.audio",
  transcoderVideo: "transcoder.video",
  waveformGenerate: "waveform.generate",
  assetOptimizerMesh: "asset_optimizer.mesh",
  fileDelete: "file.delete",
  emailSend: "email.send",
  emailAuth: "email.auth",
  emailCampaign: "email.campaign",
  userDeleteIdentity: "user.delete.identity",
  userDeleteAvatar: "user.delete.avatar",
  aiMetadataGenerate: "ai.metadata.generate",
  translationGenerate: "translation.generate",
  transcodeResult: "transcode.result",
  waveformResult: "waveform.result",
  meshOptimizationResult: "mesh.optimization.result",
  releaseTrackOriginalAudioProjection:
    "release.track_original_audio.projection",
} as const;

export const FileIngestSignalTypes = {
  upload: "upload",
  download: "download",
  finalized: "finalized",
  attached: "attached",
  failed: "failed",
} as const;

/**
 * Content type constants
 */
export const ContentType = {
  protobuf: "application/x-protobuf",
  json: "application/json",
} as const;
