// Code generated by scripts/generated/generate-spicedb-catalog.mjs.
// DO NOT EDIT.
//
// This executable contract references every generated typed Go constructor.
// The catalog generator and Go deadcode check jointly reject an untested key.

package contracttest_test

import (
	"testing"

	policyv1 "github.com/echovisionlab/geul-event-contracts/gen/api/policy/v1"
)

func TestGeneratedSpiceDBTypedSurface(t *testing.T) {
	const resourceID = "resource-id"

	actor, err := policyv1.NewAccountIdentityActor("account-identity-id")
	if err != nil {
		t.Fatal(err)
	}
	if !actor.Valid() || actor.AccountIdentityID() != "account-identity-id" {
		t.Fatalf("unexpected generated actor: %#v", actor)
	}

	direct, err := policyv1.DirectSession("session-id")
	if err != nil {
		t.Fatal(err)
	}
	assertDelegation(t, "DirectSession", policyv1.DelegationDirectSession, "session-id", "", "", direct)
	oauth, err := policyv1.MCPOAuth("oauth-client-id", "Example Member · Example Client")
	if err != nil {
		t.Fatal(err)
	}
	assertDelegation(t, "MCPOAuth", policyv1.DelegationMCPOAuth, "", "oauth-client-id", "Example Member · Example Client", oauth)
	decisionCan, err := policyv1.Platform.IsUser()
	if err != nil {
		t.Fatal(err)
	}
	decision, err := policyv1.NewAuthorizationDecision(actor, oauth, decisionCan)
	if err != nil {
		t.Fatal(err)
	}
	if !decision.Valid() || decision.Actor().AccountIdentityID() != actor.AccountIdentityID() ||
		decision.Delegation().DelegationID() != oauth.DelegationID() ||
		decision.Resource().Type() != "platform" || decision.Resource().ID() != "global" ||
		decision.Action().Name() != "is_user" || decision.Action().Permission() != "is_user" ||
		decision.EngineKey() != decisionCan.EngineKey() {
		t.Fatalf("unexpected generated authorization decision: %#v", decision)
	}

	assertRole(t, "Role.Admin", "admin", policyv1.Role.Admin())
	parsedAdmin, ok := policyv1.Role.Parse("admin")
	if !ok {
		t.Fatalf("Role.Parse(admin) rejected a generated role")
	}
	assertRole(t, "Role.Parse(admin)", "admin", parsedAdmin)
	assertRole(t, "Role.Author", "author", policyv1.Role.Author())
	parsedAuthor, ok := policyv1.Role.Parse("author")
	if !ok {
		t.Fatalf("Role.Parse(author) rejected a generated role")
	}
	assertRole(t, "Role.Parse(author)", "author", parsedAuthor)
	assertRole(t, "Role.User", "user", policyv1.Role.User())
	parsedUser, ok := policyv1.Role.Parse("user")
	if !ok {
		t.Fatalf("Role.Parse(user) rejected a generated role")
	}
	assertRole(t, "Role.Parse(user)", "user", parsedUser)
	assertRelationship(t, "Role.TouchMember", "role", "admin", "member", "account_identity", "account-identity-id", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) {
		return policyv1.Role.TouchMember(policyv1.Role.Admin(), actor)
	})
	assertRelationship(t, "Role.DeleteMember", "role", "admin", "member", "account_identity", "account-identity-id", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) {
		return policyv1.Role.DeleteMember(policyv1.Role.Admin(), actor)
	})
	assertRelationship(t, "Role.TouchAuthorIncludesAdmin", "role", "author", "member", "role", "admin", "member", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Role.TouchAuthorIncludesAdmin() })
	assertRelationship(t, "Role.DeleteAuthorIncludesAdmin", "role", "author", "member", "role", "admin", "member", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Role.DeleteAuthorIncludesAdmin() })
	assertRelationship(t, "Role.TouchUserIncludesAuthor", "role", "user", "member", "role", "author", "member", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Role.TouchUserIncludesAuthor() })
	assertRelationship(t, "Role.DeleteUserIncludesAuthor", "role", "user", "member", "role", "author", "member", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Role.DeleteUserIncludesAuthor() })
	assertResourceValue(t, "Platform.Resource", "platform", "global", policyv1.Platform.Resource())
	assertCan(t, "Platform.IsAdmin", "platform", "global", "is_admin", "is_admin", func() (policyv1.Can, error) { return policyv1.Platform.IsAdmin() })
	assertCan(t, "Platform.IsAuthor", "platform", "global", "is_author", "is_author", func() (policyv1.Can, error) { return policyv1.Platform.IsAuthor() })
	assertCan(t, "Platform.IsUser", "platform", "global", "is_user", "is_user", func() (policyv1.Can, error) { return policyv1.Platform.IsUser() })
	assertSubjectLookup(t, "Platform.LookupAdminSubjects", "platform", "global", "is_admin", "account_identity", policyv1.Platform.LookupAdminSubjects())
	assertSubjectLookup(t, "Platform.LookupAuthorSubjects", "platform", "global", "is_author", "account_identity", policyv1.Platform.LookupAuthorSubjects())
	assertSubjectLookup(t, "Platform.LookupUserSubjects", "platform", "global", "is_user", "account_identity", policyv1.Platform.LookupUserSubjects())
	assertRelationship(t, "Platform.TouchAdminRole", "platform", "global", "admin", "role", "admin", "member", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Platform.TouchAdminRole() })
	assertRelationship(t, "Platform.DeleteAdminRole", "platform", "global", "admin", "role", "admin", "member", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Platform.DeleteAdminRole() })
	assertRelationship(t, "Platform.TouchAuthorRole", "platform", "global", "author", "role", "author", "member", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Platform.TouchAuthorRole() })
	assertRelationship(t, "Platform.DeleteAuthorRole", "platform", "global", "author", "role", "author", "member", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Platform.DeleteAuthorRole() })
	assertRelationship(t, "Platform.TouchUserRole", "platform", "global", "user", "role", "user", "member", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Platform.TouchUserRole() })
	assertRelationship(t, "Platform.DeleteUserRole", "platform", "global", "user", "role", "user", "member", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Platform.DeleteUserRole() })
	assertResource(t, "Post.Resource", "post", resourceID, func() (policyv1.Resource, error) { return policyv1.Post.Resource(resourceID) })
	assertResourceLookup(t, "Post.LookupView", "post", "view", policyv1.Post.LookupView())
	assertResourceLookup(t, "Post.LookupEdit", "post", "edit", policyv1.Post.LookupEdit())
	assertResourceLookup(t, "Post.LookupDelete", "post", "delete", policyv1.Post.LookupDelete())
	assertResourceLookup(t, "Post.LookupPublish", "post", "publish", policyv1.Post.LookupPublish())
	assertResourceLookup(t, "Post.LookupManage", "post", "manage", policyv1.Post.LookupManage())
	assertResourceLookup(t, "Post.LookupManageParticipants", "post", "manage_participants", policyv1.Post.LookupManageParticipants())
	assertResourceLookup(t, "Post.LookupManageShareLinks", "post", "manage_share_links", policyv1.Post.LookupManageShareLinks())
	assertResourceLookup(t, "Post.LookupPlatformAdmin", "post", "platform_admin", policyv1.Post.LookupPlatformAdmin())
	assertResourceLookup(t, "Post.LookupViewArchived", "post", "view_archived", policyv1.Post.LookupViewArchived())
	assertResourceLookup(t, "Post.LookupEditArchived", "post", "edit_archived", policyv1.Post.LookupEditArchived())
	assertCan(t, "Post.Edit", "post", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.Post.Edit(resourceID) })
	assertCan(t, "Post.View", "post", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.Post.View(resourceID) })
	assertCan(t, "Post.ViewArchived", "post", resourceID, "view_archived", "view_archived", func() (policyv1.Can, error) { return policyv1.Post.ViewArchived(resourceID) })
	assertCan(t, "Post.EditArchived", "post", resourceID, "edit_archived", "edit_archived", func() (policyv1.Can, error) { return policyv1.Post.EditArchived(resourceID) })
	assertCan(t, "Post.Delete", "post", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.Post.Delete(resourceID) })
	assertCan(t, "Post.Publish", "post", resourceID, "publish", "publish", func() (policyv1.Can, error) { return policyv1.Post.Publish(resourceID) })
	assertCan(t, "Post.Manage", "post", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.Post.Manage(resourceID) })
	assertCan(t, "Post.ManageParticipants", "post", resourceID, "manage_participants", "manage_participants", func() (policyv1.Can, error) { return policyv1.Post.ManageParticipants(resourceID) })
	assertCan(t, "Post.ManageShareLinks", "post", resourceID, "manage_share_links", "manage_share_links", func() (policyv1.Can, error) { return policyv1.Post.ManageShareLinks(resourceID) })
	assertCan(t, "Post.RemoveAuthor", "post", resourceID, "remove_author", "platform_admin", func() (policyv1.Can, error) { return policyv1.Post.RemoveAuthor(resourceID) })
	assertCan(t, "Post.Create", "platform", "global", "post.create", "is_author", func() (policyv1.Can, error) { return policyv1.Post.Create() })
	assertCan(t, "Post.List", "platform", "global", "post.list", "is_admin", func() (policyv1.Can, error) { return policyv1.Post.List() })
	assertRelationship(t, "Post.TouchPolicy", "post", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Post.TouchPolicy(resourceID) })
	assertRelationship(t, "Post.DeletePolicy", "post", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Post.DeletePolicy(resourceID) })
	assertRelationship(t, "Post.TouchAuthor", "post", resourceID, "author", "account_identity", "account-identity-id", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Post.TouchAuthor(resourceID, actor) })
	assertRelationship(t, "Post.DeleteAuthor", "post", resourceID, "author", "account_identity", "account-identity-id", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Post.DeleteAuthor(resourceID, actor) })
	assertRelationship(t, "Post.TouchCollaborator", "post", resourceID, "collaborator", "account_identity", "account-identity-id", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) {
		return policyv1.Post.TouchCollaborator(resourceID, actor)
	})
	assertRelationship(t, "Post.DeleteCollaborator", "post", resourceID, "collaborator", "account_identity", "account-identity-id", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) {
		return policyv1.Post.DeleteCollaborator(resourceID, actor)
	})
	assertResource(t, "Artist.Resource", "artist", resourceID, func() (policyv1.Resource, error) { return policyv1.Artist.Resource(resourceID) })
	assertResourceLookup(t, "Artist.LookupManage", "artist", "manage", policyv1.Artist.LookupManage())
	assertCan(t, "Artist.Edit", "artist", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.Artist.Edit(resourceID) })
	assertCan(t, "Artist.View", "artist", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.Artist.View(resourceID) })
	assertCan(t, "Artist.Delete", "artist", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.Artist.Delete(resourceID) })
	assertCan(t, "Artist.Publish", "artist", resourceID, "publish", "publish", func() (policyv1.Can, error) { return policyv1.Artist.Publish(resourceID) })
	assertCan(t, "Artist.Manage", "artist", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.Artist.Manage(resourceID) })
	assertCan(t, "Artist.ManageParticipants", "artist", resourceID, "manage_participants", "manage_participants", func() (policyv1.Can, error) { return policyv1.Artist.ManageParticipants(resourceID) })
	assertCan(t, "Artist.ManageShareLinks", "artist", resourceID, "manage_share_links", "manage_share_links", func() (policyv1.Can, error) { return policyv1.Artist.ManageShareLinks(resourceID) })
	assertCan(t, "Artist.RemoveOwner", "artist", resourceID, "remove_owner", "platform_admin", func() (policyv1.Can, error) { return policyv1.Artist.RemoveOwner(resourceID) })
	assertCan(t, "Artist.Create", "platform", "global", "artist.create", "is_admin", func() (policyv1.Can, error) { return policyv1.Artist.Create() })
	assertCan(t, "Artist.List", "platform", "global", "artist.list", "is_admin", func() (policyv1.Can, error) { return policyv1.Artist.List() })
	assertRelationship(t, "Artist.TouchPolicy", "artist", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Artist.TouchPolicy(resourceID) })
	assertRelationship(t, "Artist.DeletePolicy", "artist", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Artist.DeletePolicy(resourceID) })
	assertRelationship(t, "Artist.TouchOwner", "artist", resourceID, "owner", "account_identity", "account-identity-id", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Artist.TouchOwner(resourceID, actor) })
	assertRelationship(t, "Artist.DeleteOwner", "artist", resourceID, "owner", "account_identity", "account-identity-id", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Artist.DeleteOwner(resourceID, actor) })
	assertRelationship(t, "Artist.TouchManager", "artist", resourceID, "manager", "account_identity", "account-identity-id", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Artist.TouchManager(resourceID, actor) })
	assertRelationship(t, "Artist.DeleteManager", "artist", resourceID, "manager", "account_identity", "account-identity-id", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Artist.DeleteManager(resourceID, actor) })
	assertRelationship(t, "Artist.TouchParent", "artist", resourceID, "parent", "artist", "parent-subject-id", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) {
		return policyv1.Artist.TouchParent(resourceID, "parent-subject-id")
	})
	assertRelationship(t, "Artist.DeleteParent", "artist", resourceID, "parent", "artist", "parent-subject-id", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) {
		return policyv1.Artist.DeleteParent(resourceID, "parent-subject-id")
	})
	assertResource(t, "Label.Resource", "label", resourceID, func() (policyv1.Resource, error) { return policyv1.Label.Resource(resourceID) })
	assertCan(t, "Label.Edit", "label", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.Label.Edit(resourceID) })
	assertCan(t, "Label.View", "label", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.Label.View(resourceID) })
	assertCan(t, "Label.Delete", "label", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.Label.Delete(resourceID) })
	assertCan(t, "Label.Publish", "label", resourceID, "publish", "publish", func() (policyv1.Can, error) { return policyv1.Label.Publish(resourceID) })
	assertCan(t, "Label.Manage", "label", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.Label.Manage(resourceID) })
	assertCan(t, "Label.ManageParticipants", "label", resourceID, "manage_participants", "manage_participants", func() (policyv1.Can, error) { return policyv1.Label.ManageParticipants(resourceID) })
	assertCan(t, "Label.ManageShareLinks", "label", resourceID, "manage_share_links", "manage_share_links", func() (policyv1.Can, error) { return policyv1.Label.ManageShareLinks(resourceID) })
	assertCan(t, "Label.RemoveOwner", "label", resourceID, "remove_owner", "platform_admin", func() (policyv1.Can, error) { return policyv1.Label.RemoveOwner(resourceID) })
	assertCan(t, "Label.Create", "platform", "global", "label.create", "is_admin", func() (policyv1.Can, error) { return policyv1.Label.Create() })
	assertCan(t, "Label.List", "platform", "global", "label.list", "is_admin", func() (policyv1.Can, error) { return policyv1.Label.List() })
	assertRelationship(t, "Label.TouchPolicy", "label", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Label.TouchPolicy(resourceID) })
	assertRelationship(t, "Label.DeletePolicy", "label", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Label.DeletePolicy(resourceID) })
	assertRelationship(t, "Label.TouchOwner", "label", resourceID, "owner", "account_identity", "account-identity-id", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Label.TouchOwner(resourceID, actor) })
	assertRelationship(t, "Label.DeleteOwner", "label", resourceID, "owner", "account_identity", "account-identity-id", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Label.DeleteOwner(resourceID, actor) })
	assertRelationship(t, "Label.TouchManager", "label", resourceID, "manager", "account_identity", "account-identity-id", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Label.TouchManager(resourceID, actor) })
	assertRelationship(t, "Label.DeleteManager", "label", resourceID, "manager", "account_identity", "account-identity-id", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Label.DeleteManager(resourceID, actor) })
	assertRelationship(t, "Label.TouchParent", "label", resourceID, "parent", "label", "parent-subject-id", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) {
		return policyv1.Label.TouchParent(resourceID, "parent-subject-id")
	})
	assertRelationship(t, "Label.DeleteParent", "label", resourceID, "parent", "label", "parent-subject-id", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) {
		return policyv1.Label.DeleteParent(resourceID, "parent-subject-id")
	})
	assertResource(t, "PostSeries.Resource", "series", resourceID, func() (policyv1.Resource, error) { return policyv1.PostSeries.Resource(resourceID) })
	assertResourceLookup(t, "PostSeries.LookupView", "series", "view", policyv1.PostSeries.LookupView())
	assertResourceLookup(t, "PostSeries.LookupManage", "series", "manage", policyv1.PostSeries.LookupManage())
	assertCan(t, "PostSeries.Edit", "series", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.PostSeries.Edit(resourceID) })
	assertCan(t, "PostSeries.View", "series", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.PostSeries.View(resourceID) })
	assertCan(t, "PostSeries.Delete", "series", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.PostSeries.Delete(resourceID) })
	assertCan(t, "PostSeries.Publish", "series", resourceID, "publish", "publish", func() (policyv1.Can, error) { return policyv1.PostSeries.Publish(resourceID) })
	assertCan(t, "PostSeries.Manage", "series", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.PostSeries.Manage(resourceID) })
	assertCan(t, "PostSeries.ManageParticipants", "series", resourceID, "manage_participants", "manage_participants", func() (policyv1.Can, error) { return policyv1.PostSeries.ManageParticipants(resourceID) })
	assertCan(t, "PostSeries.Create", "platform", "global", "series.create", "is_admin", func() (policyv1.Can, error) { return policyv1.PostSeries.Create() })
	assertCan(t, "PostSeries.List", "platform", "global", "series.list", "is_admin", func() (policyv1.Can, error) { return policyv1.PostSeries.List() })
	assertRelationship(t, "PostSeries.TouchPolicy", "series", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.PostSeries.TouchPolicy(resourceID) })
	assertRelationship(t, "PostSeries.DeletePolicy", "series", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.PostSeries.DeletePolicy(resourceID) })
	assertRelationship(t, "PostSeries.TouchManager", "series", resourceID, "manager", "account_identity", "account-identity-id", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) {
		return policyv1.PostSeries.TouchManager(resourceID, actor)
	})
	assertRelationship(t, "PostSeries.DeleteManager", "series", resourceID, "manager", "account_identity", "account-identity-id", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) {
		return policyv1.PostSeries.DeleteManager(resourceID, actor)
	})
	assertResource(t, "Page.Resource", "page", resourceID, func() (policyv1.Resource, error) { return policyv1.Page.Resource(resourceID) })
	assertResourceLookup(t, "Page.LookupManage", "page", "manage", policyv1.Page.LookupManage())
	assertCan(t, "Page.View", "page", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.Page.View(resourceID) })
	assertCan(t, "Page.Edit", "page", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.Page.Edit(resourceID) })
	assertCan(t, "Page.Delete", "page", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.Page.Delete(resourceID) })
	assertCan(t, "Page.Publish", "page", resourceID, "publish", "publish", func() (policyv1.Can, error) { return policyv1.Page.Publish(resourceID) })
	assertCan(t, "Page.Manage", "page", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.Page.Manage(resourceID) })
	assertCan(t, "Page.ManageShareLinks", "page", resourceID, "manage_share_links", "manage_share_links", func() (policyv1.Can, error) { return policyv1.Page.ManageShareLinks(resourceID) })
	assertCan(t, "Page.Create", "platform", "global", "page.create", "is_admin", func() (policyv1.Can, error) { return policyv1.Page.Create() })
	assertCan(t, "Page.List", "platform", "global", "page.list", "is_admin", func() (policyv1.Can, error) { return policyv1.Page.List() })
	assertRelationship(t, "Page.TouchPolicy", "page", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Page.TouchPolicy(resourceID) })
	assertRelationship(t, "Page.DeletePolicy", "page", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Page.DeletePolicy(resourceID) })
	assertResource(t, "Work.Resource", "work", resourceID, func() (policyv1.Resource, error) { return policyv1.Work.Resource(resourceID) })
	assertResourceLookup(t, "Work.LookupManage", "work", "manage", policyv1.Work.LookupManage())
	assertCan(t, "Work.View", "work", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.Work.View(resourceID) })
	assertCan(t, "Work.Edit", "work", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.Work.Edit(resourceID) })
	assertCan(t, "Work.ViewArchived", "work", resourceID, "view_archived", "view_archived", func() (policyv1.Can, error) { return policyv1.Work.ViewArchived(resourceID) })
	assertCan(t, "Work.EditArchived", "work", resourceID, "edit_archived", "edit_archived", func() (policyv1.Can, error) { return policyv1.Work.EditArchived(resourceID) })
	assertCan(t, "Work.Delete", "work", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.Work.Delete(resourceID) })
	assertCan(t, "Work.Publish", "work", resourceID, "publish", "publish", func() (policyv1.Can, error) { return policyv1.Work.Publish(resourceID) })
	assertCan(t, "Work.Manage", "work", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.Work.Manage(resourceID) })
	assertCan(t, "Work.ManageShareLinks", "work", resourceID, "manage_share_links", "manage_share_links", func() (policyv1.Can, error) { return policyv1.Work.ManageShareLinks(resourceID) })
	assertCan(t, "Work.Create", "platform", "global", "work.create", "is_admin", func() (policyv1.Can, error) { return policyv1.Work.Create() })
	assertCan(t, "Work.List", "platform", "global", "work.list", "is_admin", func() (policyv1.Can, error) { return policyv1.Work.List() })
	assertRelationship(t, "Work.TouchPolicy", "work", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Work.TouchPolicy(resourceID) })
	assertRelationship(t, "Work.DeletePolicy", "work", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Work.DeletePolicy(resourceID) })
	assertResource(t, "Release.Resource", "release", resourceID, func() (policyv1.Resource, error) { return policyv1.Release.Resource(resourceID) })
	assertResourceLookup(t, "Release.LookupManage", "release", "manage", policyv1.Release.LookupManage())
	assertCan(t, "Release.View", "release", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.Release.View(resourceID) })
	assertCan(t, "Release.Edit", "release", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.Release.Edit(resourceID) })
	assertCan(t, "Release.Delete", "release", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.Release.Delete(resourceID) })
	assertCan(t, "Release.Publish", "release", resourceID, "publish", "publish", func() (policyv1.Can, error) { return policyv1.Release.Publish(resourceID) })
	assertCan(t, "Release.Manage", "release", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.Release.Manage(resourceID) })
	assertCan(t, "Release.ManageShareLinks", "release", resourceID, "manage_share_links", "manage_share_links", func() (policyv1.Can, error) { return policyv1.Release.ManageShareLinks(resourceID) })
	assertCan(t, "Release.Create", "platform", "global", "release.create", "is_admin", func() (policyv1.Can, error) { return policyv1.Release.Create() })
	assertCan(t, "Release.List", "platform", "global", "release.list", "is_admin", func() (policyv1.Can, error) { return policyv1.Release.List() })
	assertRelationship(t, "Release.TouchPolicy", "release", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Release.TouchPolicy(resourceID) })
	assertRelationship(t, "Release.DeletePolicy", "release", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Release.DeletePolicy(resourceID) })
	assertResource(t, "Track.Resource", "track", resourceID, func() (policyv1.Resource, error) { return policyv1.Track.Resource(resourceID) })
	assertResourceLookup(t, "Track.LookupManage", "track", "manage", policyv1.Track.LookupManage())
	assertCan(t, "Track.View", "track", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.Track.View(resourceID) })
	assertCan(t, "Track.Edit", "track", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.Track.Edit(resourceID) })
	assertCan(t, "Track.Delete", "track", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.Track.Delete(resourceID) })
	assertCan(t, "Track.Manage", "track", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.Track.Manage(resourceID) })
	assertRelationship(t, "Track.TouchPolicy", "track", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Track.TouchPolicy(resourceID) })
	assertRelationship(t, "Track.DeletePolicy", "track", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Track.DeletePolicy(resourceID) })
	assertResource(t, "ProgramEvent.Resource", "program_event", resourceID, func() (policyv1.Resource, error) { return policyv1.ProgramEvent.Resource(resourceID) })
	assertCan(t, "ProgramEvent.View", "program_event", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.ProgramEvent.View(resourceID) })
	assertCan(t, "ProgramEvent.Edit", "program_event", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.ProgramEvent.Edit(resourceID) })
	assertCan(t, "ProgramEvent.ViewArchived", "program_event", resourceID, "view_archived", "view_archived", func() (policyv1.Can, error) { return policyv1.ProgramEvent.ViewArchived(resourceID) })
	assertCan(t, "ProgramEvent.EditArchived", "program_event", resourceID, "edit_archived", "edit_archived", func() (policyv1.Can, error) { return policyv1.ProgramEvent.EditArchived(resourceID) })
	assertCan(t, "ProgramEvent.Delete", "program_event", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.ProgramEvent.Delete(resourceID) })
	assertCan(t, "ProgramEvent.Publish", "program_event", resourceID, "publish", "publish", func() (policyv1.Can, error) { return policyv1.ProgramEvent.Publish(resourceID) })
	assertCan(t, "ProgramEvent.Manage", "program_event", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.ProgramEvent.Manage(resourceID) })
	assertCan(t, "ProgramEvent.Create", "platform", "global", "program_event.create", "is_admin", func() (policyv1.Can, error) { return policyv1.ProgramEvent.Create() })
	assertCan(t, "ProgramEvent.List", "platform", "global", "program_event.list", "is_admin", func() (policyv1.Can, error) { return policyv1.ProgramEvent.List() })
	assertCan(t, "ProgramEvent.CreateType", "platform", "global", "program_event.create_type", "is_admin", func() (policyv1.Can, error) { return policyv1.ProgramEvent.CreateType() })
	assertCan(t, "ProgramEvent.ListTypes", "platform", "global", "program_event.list_types", "is_admin", func() (policyv1.Can, error) { return policyv1.ProgramEvent.ListTypes() })
	assertCan(t, "ProgramEvent.UpdateType", "platform", "global", "program_event.update_type", "is_admin", func() (policyv1.Can, error) { return policyv1.ProgramEvent.UpdateType() })
	assertCan(t, "ProgramEvent.DeleteType", "platform", "global", "program_event.delete_type", "is_admin", func() (policyv1.Can, error) { return policyv1.ProgramEvent.DeleteType() })
	assertRelationship(t, "ProgramEvent.TouchPolicy", "program_event", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.ProgramEvent.TouchPolicy(resourceID) })
	assertRelationship(t, "ProgramEvent.DeletePolicy", "program_event", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.ProgramEvent.DeletePolicy(resourceID) })
	assertResource(t, "ProgramEventSeries.Resource", "program_event_series", resourceID, func() (policyv1.Resource, error) { return policyv1.ProgramEventSeries.Resource(resourceID) })
	assertCan(t, "ProgramEventSeries.View", "program_event_series", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.ProgramEventSeries.View(resourceID) })
	assertCan(t, "ProgramEventSeries.Edit", "program_event_series", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.ProgramEventSeries.Edit(resourceID) })
	assertCan(t, "ProgramEventSeries.Delete", "program_event_series", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.ProgramEventSeries.Delete(resourceID) })
	assertCan(t, "ProgramEventSeries.Publish", "program_event_series", resourceID, "publish", "publish", func() (policyv1.Can, error) { return policyv1.ProgramEventSeries.Publish(resourceID) })
	assertCan(t, "ProgramEventSeries.Manage", "program_event_series", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.ProgramEventSeries.Manage(resourceID) })
	assertCan(t, "ProgramEventSeries.Create", "platform", "global", "program_event_series.create", "is_admin", func() (policyv1.Can, error) { return policyv1.ProgramEventSeries.Create() })
	assertCan(t, "ProgramEventSeries.List", "platform", "global", "program_event_series.list", "is_admin", func() (policyv1.Can, error) { return policyv1.ProgramEventSeries.List() })
	assertRelationship(t, "ProgramEventSeries.TouchPolicy", "program_event_series", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) {
		return policyv1.ProgramEventSeries.TouchPolicy(resourceID)
	})
	assertRelationship(t, "ProgramEventSeries.DeletePolicy", "program_event_series", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) {
		return policyv1.ProgramEventSeries.DeletePolicy(resourceID)
	})
	assertResource(t, "File.Resource", "file", resourceID, func() (policyv1.Resource, error) { return policyv1.File.Resource(resourceID) })
	assertCan(t, "File.View", "file", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.File.View(resourceID) })
	assertCan(t, "File.Edit", "file", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.File.Edit(resourceID) })
	assertCan(t, "File.Delete", "file", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.File.Delete(resourceID) })
	assertCan(t, "File.Manage", "file", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.File.Manage(resourceID) })
	assertCan(t, "File.ManageLibrary", "platform", "global", "file.manage_library", "is_admin", func() (policyv1.Can, error) { return policyv1.File.ManageLibrary() })
	assertCan(t, "File.List", "platform", "global", "file.list", "is_author", func() (policyv1.Can, error) { return policyv1.File.List() })
	assertRelationship(t, "File.TouchPolicy", "file", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.File.TouchPolicy(resourceID) })
	assertRelationship(t, "File.DeletePolicy", "file", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.File.DeletePolicy(resourceID) })
	assertResource(t, "Campaign.Resource", "campaign", resourceID, func() (policyv1.Resource, error) { return policyv1.Campaign.Resource(resourceID) })
	assertCan(t, "Campaign.View", "campaign", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.Campaign.View(resourceID) })
	assertCan(t, "Campaign.Edit", "campaign", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.Campaign.Edit(resourceID) })
	assertCan(t, "Campaign.Delete", "campaign", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.Campaign.Delete(resourceID) })
	assertCan(t, "Campaign.Manage", "campaign", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.Campaign.Manage(resourceID) })
	assertCan(t, "Campaign.Create", "platform", "global", "campaign.create", "is_admin", func() (policyv1.Can, error) { return policyv1.Campaign.Create() })
	assertCan(t, "Campaign.List", "platform", "global", "campaign.list", "is_admin", func() (policyv1.Can, error) { return policyv1.Campaign.List() })
	assertRelationship(t, "Campaign.TouchPolicy", "campaign", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Campaign.TouchPolicy(resourceID) })
	assertRelationship(t, "Campaign.DeletePolicy", "campaign", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Campaign.DeletePolicy(resourceID) })
	assertResource(t, "AudienceSegment.Resource", "audience_segment", resourceID, func() (policyv1.Resource, error) { return policyv1.AudienceSegment.Resource(resourceID) })
	assertCan(t, "AudienceSegment.View", "audience_segment", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.AudienceSegment.View(resourceID) })
	assertCan(t, "AudienceSegment.Edit", "audience_segment", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.AudienceSegment.Edit(resourceID) })
	assertCan(t, "AudienceSegment.Delete", "audience_segment", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.AudienceSegment.Delete(resourceID) })
	assertCan(t, "AudienceSegment.Manage", "audience_segment", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.AudienceSegment.Manage(resourceID) })
	assertCan(t, "AudienceSegment.Create", "platform", "global", "audience_segment.create", "is_admin", func() (policyv1.Can, error) { return policyv1.AudienceSegment.Create() })
	assertCan(t, "AudienceSegment.List", "platform", "global", "audience_segment.list", "is_admin", func() (policyv1.Can, error) { return policyv1.AudienceSegment.List() })
	assertCan(t, "AudienceSegment.ListAuthenticatedAccess", "platform", "global", "audience_segment.list_authenticated_access", "is_author", func() (policyv1.Can, error) { return policyv1.AudienceSegment.ListAuthenticatedAccess() })
	assertRelationship(t, "AudienceSegment.TouchPolicy", "audience_segment", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.AudienceSegment.TouchPolicy(resourceID) })
	assertRelationship(t, "AudienceSegment.DeletePolicy", "audience_segment", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) {
		return policyv1.AudienceSegment.DeletePolicy(resourceID)
	})
	assertResource(t, "MapPlace.Resource", "map_place", resourceID, func() (policyv1.Resource, error) { return policyv1.MapPlace.Resource(resourceID) })
	assertCan(t, "MapPlace.View", "map_place", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.MapPlace.View(resourceID) })
	assertCan(t, "MapPlace.Edit", "map_place", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.MapPlace.Edit(resourceID) })
	assertCan(t, "MapPlace.Delete", "map_place", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.MapPlace.Delete(resourceID) })
	assertCan(t, "MapPlace.Manage", "map_place", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.MapPlace.Manage(resourceID) })
	assertCan(t, "MapPlace.Create", "platform", "global", "map_place.create", "is_author", func() (policyv1.Can, error) { return policyv1.MapPlace.Create() })
	assertRelationship(t, "MapPlace.TouchPolicy", "map_place", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.MapPlace.TouchPolicy(resourceID) })
	assertRelationship(t, "MapPlace.DeletePolicy", "map_place", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.MapPlace.DeletePolicy(resourceID) })
	assertResource(t, "Category.Resource", "category", resourceID, func() (policyv1.Resource, error) { return policyv1.Category.Resource(resourceID) })
	assertCan(t, "Category.View", "category", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.Category.View(resourceID) })
	assertCan(t, "Category.Edit", "category", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.Category.Edit(resourceID) })
	assertCan(t, "Category.Delete", "category", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.Category.Delete(resourceID) })
	assertCan(t, "Category.Manage", "category", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.Category.Manage(resourceID) })
	assertCan(t, "Category.Create", "platform", "global", "category.create", "is_admin", func() (policyv1.Can, error) { return policyv1.Category.Create() })
	assertCan(t, "Category.List", "platform", "global", "category.list", "is_admin", func() (policyv1.Can, error) { return policyv1.Category.List() })
	assertRelationship(t, "Category.TouchPolicy", "category", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Category.TouchPolicy(resourceID) })
	assertRelationship(t, "Category.DeletePolicy", "category", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Category.DeletePolicy(resourceID) })
	assertResource(t, "Tag.Resource", "tag", resourceID, func() (policyv1.Resource, error) { return policyv1.Tag.Resource(resourceID) })
	assertCan(t, "Tag.View", "tag", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.Tag.View(resourceID) })
	assertCan(t, "Tag.Edit", "tag", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.Tag.Edit(resourceID) })
	assertCan(t, "Tag.Delete", "tag", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.Tag.Delete(resourceID) })
	assertCan(t, "Tag.Manage", "tag", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.Tag.Manage(resourceID) })
	assertCan(t, "Tag.Create", "platform", "global", "tag.create", "is_admin", func() (policyv1.Can, error) { return policyv1.Tag.Create() })
	assertCan(t, "Tag.List", "platform", "global", "tag.list", "is_admin", func() (policyv1.Can, error) { return policyv1.Tag.List() })
	assertRelationship(t, "Tag.TouchPolicy", "tag", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Tag.TouchPolicy(resourceID) })
	assertRelationship(t, "Tag.DeletePolicy", "tag", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Tag.DeletePolicy(resourceID) })
	assertResource(t, "Genre.Resource", "genre", resourceID, func() (policyv1.Resource, error) { return policyv1.Genre.Resource(resourceID) })
	assertCan(t, "Genre.View", "genre", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.Genre.View(resourceID) })
	assertCan(t, "Genre.Edit", "genre", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.Genre.Edit(resourceID) })
	assertCan(t, "Genre.Delete", "genre", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.Genre.Delete(resourceID) })
	assertCan(t, "Genre.Manage", "genre", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.Genre.Manage(resourceID) })
	assertCan(t, "Genre.Create", "platform", "global", "genre.create", "is_admin", func() (policyv1.Can, error) { return policyv1.Genre.Create() })
	assertCan(t, "Genre.List", "platform", "global", "genre.list", "is_admin", func() (policyv1.Can, error) { return policyv1.Genre.List() })
	assertRelationship(t, "Genre.TouchPolicy", "genre", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Genre.TouchPolicy(resourceID) })
	assertRelationship(t, "Genre.DeletePolicy", "genre", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Genre.DeletePolicy(resourceID) })
	assertResource(t, "Style.Resource", "style", resourceID, func() (policyv1.Resource, error) { return policyv1.Style.Resource(resourceID) })
	assertCan(t, "Style.View", "style", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.Style.View(resourceID) })
	assertCan(t, "Style.Edit", "style", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.Style.Edit(resourceID) })
	assertCan(t, "Style.Delete", "style", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.Style.Delete(resourceID) })
	assertCan(t, "Style.Manage", "style", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.Style.Manage(resourceID) })
	assertCan(t, "Style.Create", "platform", "global", "style.create", "is_admin", func() (policyv1.Can, error) { return policyv1.Style.Create() })
	assertCan(t, "Style.List", "platform", "global", "style.list", "is_admin", func() (policyv1.Can, error) { return policyv1.Style.List() })
	assertRelationship(t, "Style.TouchPolicy", "style", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Style.TouchPolicy(resourceID) })
	assertRelationship(t, "Style.DeletePolicy", "style", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Style.DeletePolicy(resourceID) })
	assertResource(t, "Format.Resource", "format", resourceID, func() (policyv1.Resource, error) { return policyv1.Format.Resource(resourceID) })
	assertCan(t, "Format.View", "format", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.Format.View(resourceID) })
	assertCan(t, "Format.Edit", "format", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.Format.Edit(resourceID) })
	assertCan(t, "Format.Delete", "format", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.Format.Delete(resourceID) })
	assertCan(t, "Format.Manage", "format", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.Format.Manage(resourceID) })
	assertCan(t, "Format.Create", "platform", "global", "format.create", "is_admin", func() (policyv1.Can, error) { return policyv1.Format.Create() })
	assertCan(t, "Format.List", "platform", "global", "format.list", "is_admin", func() (policyv1.Can, error) { return policyv1.Format.List() })
	assertRelationship(t, "Format.TouchPolicy", "format", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Format.TouchPolicy(resourceID) })
	assertRelationship(t, "Format.DeletePolicy", "format", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Format.DeletePolicy(resourceID) })
	assertResource(t, "Client.Resource", "client", resourceID, func() (policyv1.Resource, error) { return policyv1.Client.Resource(resourceID) })
	assertCan(t, "Client.View", "client", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.Client.View(resourceID) })
	assertCan(t, "Client.Edit", "client", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.Client.Edit(resourceID) })
	assertCan(t, "Client.Delete", "client", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.Client.Delete(resourceID) })
	assertCan(t, "Client.Manage", "client", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.Client.Manage(resourceID) })
	assertCan(t, "Client.Create", "platform", "global", "client.create", "is_admin", func() (policyv1.Can, error) { return policyv1.Client.Create() })
	assertCan(t, "Client.List", "platform", "global", "client.list", "is_admin", func() (policyv1.Can, error) { return policyv1.Client.List() })
	assertRelationship(t, "Client.TouchPolicy", "client", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Client.TouchPolicy(resourceID) })
	assertRelationship(t, "Client.DeletePolicy", "client", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Client.DeletePolicy(resourceID) })
	assertResource(t, "SiteSetting.Resource", "site_setting", resourceID, func() (policyv1.Resource, error) { return policyv1.SiteSetting.Resource(resourceID) })
	assertCan(t, "SiteSetting.View", "site_setting", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.SiteSetting.View(resourceID) })
	assertCan(t, "SiteSetting.Edit", "site_setting", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.SiteSetting.Edit(resourceID) })
	assertCan(t, "SiteSetting.Delete", "site_setting", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.SiteSetting.Delete(resourceID) })
	assertCan(t, "SiteSetting.Manage", "site_setting", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.SiteSetting.Manage(resourceID) })
	assertRelationship(t, "SiteSetting.TouchPolicy", "site_setting", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.SiteSetting.TouchPolicy(resourceID) })
	assertRelationship(t, "SiteSetting.DeletePolicy", "site_setting", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.SiteSetting.DeletePolicy(resourceID) })
	assertResource(t, "Menu.Resource", "menu", resourceID, func() (policyv1.Resource, error) { return policyv1.Menu.Resource(resourceID) })
	assertCan(t, "Menu.View", "menu", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.Menu.View(resourceID) })
	assertCan(t, "Menu.Edit", "menu", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.Menu.Edit(resourceID) })
	assertCan(t, "Menu.Delete", "menu", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.Menu.Delete(resourceID) })
	assertCan(t, "Menu.Manage", "menu", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.Menu.Manage(resourceID) })
	assertCan(t, "Menu.Create", "platform", "global", "menu.create", "is_admin", func() (policyv1.Can, error) { return policyv1.Menu.Create() })
	assertCan(t, "Menu.List", "platform", "global", "menu.list", "is_admin", func() (policyv1.Can, error) { return policyv1.Menu.List() })
	assertRelationship(t, "Menu.TouchPolicy", "menu", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Menu.TouchPolicy(resourceID) })
	assertRelationship(t, "Menu.DeletePolicy", "menu", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Menu.DeletePolicy(resourceID) })
	assertResource(t, "Member.Resource", "member", resourceID, func() (policyv1.Resource, error) { return policyv1.Member.Resource(resourceID) })
	assertCan(t, "Member.View", "member", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.Member.View(resourceID) })
	assertCan(t, "Member.Edit", "member", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.Member.Edit(resourceID) })
	assertCan(t, "Member.Delete", "member", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.Member.Delete(resourceID) })
	assertCan(t, "Member.Manage", "member", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.Member.Manage(resourceID) })
	assertCan(t, "Member.List", "platform", "global", "member.list", "is_admin", func() (policyv1.Can, error) { return policyv1.Member.List() })
	assertRelationship(t, "Member.TouchPolicy", "member", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Member.TouchPolicy(resourceID) })
	assertRelationship(t, "Member.DeletePolicy", "member", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Member.DeletePolicy(resourceID) })
	assertResource(t, "Form.Resource", "form", resourceID, func() (policyv1.Resource, error) { return policyv1.Form.Resource(resourceID) })
	assertResourceLookup(t, "Form.LookupManage", "form", "manage", policyv1.Form.LookupManage())
	assertCan(t, "Form.View", "form", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.Form.View(resourceID) })
	assertCan(t, "Form.Edit", "form", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.Form.Edit(resourceID) })
	assertCan(t, "Form.Delete", "form", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.Form.Delete(resourceID) })
	assertCan(t, "Form.Publish", "form", resourceID, "publish", "publish", func() (policyv1.Can, error) { return policyv1.Form.Publish(resourceID) })
	assertCan(t, "Form.Manage", "form", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.Form.Manage(resourceID) })
	assertCan(t, "Form.ManageShareLinks", "form", resourceID, "manage_share_links", "manage_share_links", func() (policyv1.Can, error) { return policyv1.Form.ManageShareLinks(resourceID) })
	assertCan(t, "Form.Create", "platform", "global", "form.create", "is_admin", func() (policyv1.Can, error) { return policyv1.Form.Create() })
	assertCan(t, "Form.List", "platform", "global", "form.list", "is_admin", func() (policyv1.Can, error) { return policyv1.Form.List() })
	assertRelationship(t, "Form.TouchPolicy", "form", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.Form.TouchPolicy(resourceID) })
	assertRelationship(t, "Form.DeletePolicy", "form", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.Form.DeletePolicy(resourceID) })
	assertResource(t, "EmailTemplate.Resource", "email_template", resourceID, func() (policyv1.Resource, error) { return policyv1.EmailTemplate.Resource(resourceID) })
	assertCan(t, "EmailTemplate.View", "email_template", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.EmailTemplate.View(resourceID) })
	assertCan(t, "EmailTemplate.Edit", "email_template", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.EmailTemplate.Edit(resourceID) })
	assertCan(t, "EmailTemplate.Delete", "email_template", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.EmailTemplate.Delete(resourceID) })
	assertCan(t, "EmailTemplate.Manage", "email_template", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.EmailTemplate.Manage(resourceID) })
	assertCan(t, "EmailTemplate.Create", "platform", "global", "email_template.create", "is_admin", func() (policyv1.Can, error) { return policyv1.EmailTemplate.Create() })
	assertCan(t, "EmailTemplate.List", "platform", "global", "email_template.list", "is_admin", func() (policyv1.Can, error) { return policyv1.EmailTemplate.List() })
	assertRelationship(t, "EmailTemplate.TouchPolicy", "email_template", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.EmailTemplate.TouchPolicy(resourceID) })
	assertRelationship(t, "EmailTemplate.DeletePolicy", "email_template", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.EmailTemplate.DeletePolicy(resourceID) })
	assertResource(t, "EmailLayout.Resource", "email_layout", resourceID, func() (policyv1.Resource, error) { return policyv1.EmailLayout.Resource(resourceID) })
	assertCan(t, "EmailLayout.View", "email_layout", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.EmailLayout.View(resourceID) })
	assertCan(t, "EmailLayout.Edit", "email_layout", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.EmailLayout.Edit(resourceID) })
	assertCan(t, "EmailLayout.Delete", "email_layout", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.EmailLayout.Delete(resourceID) })
	assertCan(t, "EmailLayout.Manage", "email_layout", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.EmailLayout.Manage(resourceID) })
	assertCan(t, "EmailLayout.Create", "platform", "global", "email_layout.create", "is_admin", func() (policyv1.Can, error) { return policyv1.EmailLayout.Create() })
	assertCan(t, "EmailLayout.List", "platform", "global", "email_layout.list", "is_admin", func() (policyv1.Can, error) { return policyv1.EmailLayout.List() })
	assertCan(t, "EmailLayout.PreviewContent", "platform", "global", "email_layout.preview_content", "is_admin", func() (policyv1.Can, error) { return policyv1.EmailLayout.PreviewContent() })
	assertRelationship(t, "EmailLayout.TouchPolicy", "email_layout", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.EmailLayout.TouchPolicy(resourceID) })
	assertRelationship(t, "EmailLayout.DeletePolicy", "email_layout", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.EmailLayout.DeletePolicy(resourceID) })
	assertResource(t, "EmailEventMapping.Resource", "email_event_mapping", resourceID, func() (policyv1.Resource, error) { return policyv1.EmailEventMapping.Resource(resourceID) })
	assertCan(t, "EmailEventMapping.Update", "platform", "global", "email_event_mapping.update", "is_admin", func() (policyv1.Can, error) { return policyv1.EmailEventMapping.Update() })
	assertResource(t, "MailAdapter.Resource", "mail_adapter", resourceID, func() (policyv1.Resource, error) { return policyv1.MailAdapter.Resource(resourceID) })
	assertCan(t, "MailAdapter.List", "platform", "global", "mail_adapter.list", "is_admin", func() (policyv1.Can, error) { return policyv1.MailAdapter.List() })
	assertCan(t, "MailAdapter.Create", "platform", "global", "mail_adapter.create", "is_admin", func() (policyv1.Can, error) { return policyv1.MailAdapter.Create() })
	assertCan(t, "MailAdapter.Update", "platform", "global", "mail_adapter.update", "is_admin", func() (policyv1.Can, error) { return policyv1.MailAdapter.Update() })
	assertCan(t, "MailAdapter.Delete", "platform", "global", "mail_adapter.delete", "is_admin", func() (policyv1.Can, error) { return policyv1.MailAdapter.Delete() })
	assertCan(t, "MailAdapter.Test", "platform", "global", "mail_adapter.test", "is_admin", func() (policyv1.Can, error) { return policyv1.MailAdapter.Test() })
	assertResource(t, "EmailSuppression.Resource", "email_suppression", resourceID, func() (policyv1.Resource, error) { return policyv1.EmailSuppression.Resource(resourceID) })
	assertCan(t, "EmailSuppression.Release", "platform", "global", "email_suppression.release", "is_admin", func() (policyv1.Can, error) { return policyv1.EmailSuppression.Release() })
	assertResource(t, "TranslationSettings.Resource", "translation_settings", resourceID, func() (policyv1.Resource, error) { return policyv1.TranslationSettings.Resource(resourceID) })
	assertCan(t, "TranslationSettings.View", "platform", "global", "translation_settings.view", "is_admin", func() (policyv1.Can, error) { return policyv1.TranslationSettings.View() })
	assertCan(t, "TranslationSettings.Update", "platform", "global", "translation_settings.update", "is_admin", func() (policyv1.Can, error) { return policyv1.TranslationSettings.Update() })
	assertResource(t, "TranslationProvider.Resource", "translation_provider", resourceID, func() (policyv1.Resource, error) { return policyv1.TranslationProvider.Resource(resourceID) })
	assertCan(t, "TranslationProvider.List", "platform", "global", "translation_provider.list", "is_admin", func() (policyv1.Can, error) { return policyv1.TranslationProvider.List() })
	assertCan(t, "TranslationProvider.Create", "platform", "global", "translation_provider.create", "is_admin", func() (policyv1.Can, error) { return policyv1.TranslationProvider.Create() })
	assertCan(t, "TranslationProvider.Update", "platform", "global", "translation_provider.update", "is_admin", func() (policyv1.Can, error) { return policyv1.TranslationProvider.Update() })
	assertCan(t, "TranslationProvider.Delete", "platform", "global", "translation_provider.delete", "is_admin", func() (policyv1.Can, error) { return policyv1.TranslationProvider.Delete() })
	assertResource(t, "TermsHistory.Resource", "terms_history", resourceID, func() (policyv1.Resource, error) { return policyv1.TermsHistory.Resource(resourceID) })
	assertCan(t, "TermsHistory.View", "terms_history", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.TermsHistory.View(resourceID) })
	assertCan(t, "TermsHistory.Edit", "terms_history", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.TermsHistory.Edit(resourceID) })
	assertCan(t, "TermsHistory.ViewArchived", "terms_history", resourceID, "view_archived", "view_archived", func() (policyv1.Can, error) { return policyv1.TermsHistory.ViewArchived(resourceID) })
	assertCan(t, "TermsHistory.EditArchived", "terms_history", resourceID, "edit_archived", "edit_archived", func() (policyv1.Can, error) { return policyv1.TermsHistory.EditArchived(resourceID) })
	assertCan(t, "TermsHistory.Delete", "terms_history", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.TermsHistory.Delete(resourceID) })
	assertCan(t, "TermsHistory.Publish", "terms_history", resourceID, "publish", "publish", func() (policyv1.Can, error) { return policyv1.TermsHistory.Publish(resourceID) })
	assertCan(t, "TermsHistory.Manage", "terms_history", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.TermsHistory.Manage(resourceID) })
	assertCan(t, "TermsHistory.ManageShareLinks", "terms_history", resourceID, "manage_share_links", "manage_share_links", func() (policyv1.Can, error) { return policyv1.TermsHistory.ManageShareLinks(resourceID) })
	assertCan(t, "TermsHistory.Create", "platform", "global", "terms_history.create", "is_admin", func() (policyv1.Can, error) { return policyv1.TermsHistory.Create() })
	assertCan(t, "TermsHistory.List", "platform", "global", "terms_history.list", "is_admin", func() (policyv1.Can, error) { return policyv1.TermsHistory.List() })
	assertRelationship(t, "TermsHistory.TouchPolicy", "terms_history", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.TermsHistory.TouchPolicy(resourceID) })
	assertRelationship(t, "TermsHistory.DeletePolicy", "terms_history", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.TermsHistory.DeletePolicy(resourceID) })
	assertResource(t, "PrivacyHistory.Resource", "privacy_history", resourceID, func() (policyv1.Resource, error) { return policyv1.PrivacyHistory.Resource(resourceID) })
	assertCan(t, "PrivacyHistory.View", "privacy_history", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.PrivacyHistory.View(resourceID) })
	assertCan(t, "PrivacyHistory.Edit", "privacy_history", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.PrivacyHistory.Edit(resourceID) })
	assertCan(t, "PrivacyHistory.ViewArchived", "privacy_history", resourceID, "view_archived", "view_archived", func() (policyv1.Can, error) { return policyv1.PrivacyHistory.ViewArchived(resourceID) })
	assertCan(t, "PrivacyHistory.EditArchived", "privacy_history", resourceID, "edit_archived", "edit_archived", func() (policyv1.Can, error) { return policyv1.PrivacyHistory.EditArchived(resourceID) })
	assertCan(t, "PrivacyHistory.Delete", "privacy_history", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.PrivacyHistory.Delete(resourceID) })
	assertCan(t, "PrivacyHistory.Publish", "privacy_history", resourceID, "publish", "publish", func() (policyv1.Can, error) { return policyv1.PrivacyHistory.Publish(resourceID) })
	assertCan(t, "PrivacyHistory.Manage", "privacy_history", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.PrivacyHistory.Manage(resourceID) })
	assertCan(t, "PrivacyHistory.ManageShareLinks", "privacy_history", resourceID, "manage_share_links", "manage_share_links", func() (policyv1.Can, error) { return policyv1.PrivacyHistory.ManageShareLinks(resourceID) })
	assertCan(t, "PrivacyHistory.Create", "platform", "global", "privacy_history.create", "is_admin", func() (policyv1.Can, error) { return policyv1.PrivacyHistory.Create() })
	assertCan(t, "PrivacyHistory.List", "platform", "global", "privacy_history.list", "is_admin", func() (policyv1.Can, error) { return policyv1.PrivacyHistory.List() })
	assertRelationship(t, "PrivacyHistory.TouchPolicy", "privacy_history", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.PrivacyHistory.TouchPolicy(resourceID) })
	assertRelationship(t, "PrivacyHistory.DeletePolicy", "privacy_history", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.PrivacyHistory.DeletePolicy(resourceID) })
	assertResource(t, "MapTheme.Resource", "map_theme", resourceID, func() (policyv1.Resource, error) { return policyv1.MapTheme.Resource(resourceID) })
	assertCan(t, "MapTheme.View", "map_theme", resourceID, "view", "view", func() (policyv1.Can, error) { return policyv1.MapTheme.View(resourceID) })
	assertCan(t, "MapTheme.Edit", "map_theme", resourceID, "edit", "edit", func() (policyv1.Can, error) { return policyv1.MapTheme.Edit(resourceID) })
	assertCan(t, "MapTheme.Delete", "map_theme", resourceID, "delete", "delete", func() (policyv1.Can, error) { return policyv1.MapTheme.Delete(resourceID) })
	assertCan(t, "MapTheme.Manage", "map_theme", resourceID, "manage", "manage", func() (policyv1.Can, error) { return policyv1.MapTheme.Manage(resourceID) })
	assertCan(t, "MapTheme.Create", "platform", "global", "map_theme.create", "is_admin", func() (policyv1.Can, error) { return policyv1.MapTheme.Create() })
	assertRelationship(t, "MapTheme.TouchPolicy", "map_theme", resourceID, "policy", "platform", "global", "", policyv1.RelationshipTouch, func() (policyv1.RelationshipMutation, error) { return policyv1.MapTheme.TouchPolicy(resourceID) })
	assertRelationship(t, "MapTheme.DeletePolicy", "map_theme", resourceID, "policy", "platform", "global", "", policyv1.RelationshipDelete, func() (policyv1.RelationshipMutation, error) { return policyv1.MapTheme.DeletePolicy(resourceID) })
}

func assertDelegation(t *testing.T, name string, kind policyv1.DelegationKind, sessionID, delegationID, displayName string, delegation policyv1.Delegation) {
	t.Helper()
	if !delegation.Valid() || delegation.Kind() != kind || delegation.SessionID() != sessionID ||
		delegation.DelegationID() != delegationID || delegation.DelegationDisplayName() != displayName {
		t.Fatalf("%s returned an unexpected delegation: %#v", name, delegation)
	}
}

func assertRole(t *testing.T, name, id string, role policyv1.RoleID) {
	t.Helper()
	if !role.Valid() || role.ID() != id {
		t.Fatalf("%s returned an unexpected role: %#v", name, role)
	}
}

func assertResource(t *testing.T, name, resourceType, resourceID string, construct func() (policyv1.Resource, error)) {
	t.Helper()
	resource, err := construct()
	if err != nil {
		t.Fatalf("%s: %v", name, err)
	}
	assertResourceValue(t, name, resourceType, resourceID, resource)
}

func assertResourceValue(t *testing.T, name, resourceType, resourceID string, resource policyv1.Resource) {
	t.Helper()
	if !resource.Valid() || resource.Type() != resourceType || resource.ID() != resourceID {
		t.Fatalf("%s returned an unexpected resource: %#v", name, resource)
	}
}

func assertResourceLookup(t *testing.T, name, resourceType, permission string, lookup policyv1.ResourceLookup) {
	t.Helper()
	if !lookup.Valid() || lookup.ResourceType() != resourceType || lookup.Permission() != permission {
		t.Fatalf("%s returned an unexpected resource lookup: %#v", name, lookup)
	}
}

func assertSubjectLookup(t *testing.T, name, resourceType, resourceID, permission, subjectType string, lookup policyv1.SubjectLookup) {
	t.Helper()
	if !lookup.Valid() || lookup.ResourceType() != resourceType || lookup.ResourceID() != resourceID ||
		lookup.Permission() != permission || lookup.SubjectType() != subjectType {
		t.Fatalf("%s returned an unexpected subject lookup: %#v", name, lookup)
	}
}

func assertCan(t *testing.T, name, resourceType, resourceID, actionName, permission string, construct func() (policyv1.Can, error)) {
	t.Helper()
	can, err := construct()
	if err != nil {
		t.Fatalf("%s: %v", name, err)
	}
	if !can.Valid() || !can.Resource().Valid() || !can.Action().Valid() ||
		can.Resource().Type() != resourceType || can.Resource().ID() != resourceID ||
		can.Action().Name() != actionName || can.Action().Permission() != permission ||
		can.EngineKey() != resourceType+"\x00"+resourceID+"\x00"+permission {
		t.Fatalf("%s returned an unexpected can descriptor: %#v", name, can)
	}
}

func assertRelationship(t *testing.T, name, resourceType, resourceID, relation, subjectType, subjectID, subjectRelation string, operation policyv1.RelationshipOperation, construct func() (policyv1.RelationshipMutation, error)) {
	t.Helper()
	mutation, err := construct()
	if err != nil {
		t.Fatalf("%s: %v", name, err)
	}
	if !mutation.Valid() || !mutation.Resource().Valid() ||
		mutation.Resource().Type() != resourceType || mutation.Resource().ID() != resourceID ||
		mutation.Relation() != relation || mutation.SubjectType() != subjectType ||
		mutation.SubjectID() != subjectID || mutation.SubjectRelation() != subjectRelation ||
		mutation.Operation() != operation {
		t.Fatalf("%s returned an unexpected relationship: %#v", name, mutation)
	}
}
